fixing addFile while original file size changes during archiving
splitbrain/php-archive pull request #17
Opened 2017-03-13 05:40 UTC by ovidiul

When adding a file which size is being changed during archiving, the archive would become corrupt because the size in the header is different than the size of the actual data written. So an additional check should be done and if the sizes are different, the header should be updated. A quick test would be to create an infinite loop where you write 1 byte to a test.txt file and then trying to add that file to the archive and extracting the archive. 

The error one would get on extraction is "Header does not match it's checksum" because the next file added would not be fetched correctly, and it's header is not seeked at the correct point.

2017-03-13 10:16 UTC, splitbrain requested changes
Could you please fix the formatting errors, check why the existing test cases break and add a specific test for the actual problem here?

2017-03-13 10:16 UTC, splitbrain commented on src/Tar.php
> +
introduced trailing whitespace

2017-03-13 10:16 UTC, splitbrain commented on src/Tar.php
> +		}
broken indentation

2017-03-13 12:16 UTC, ovidiul commented
Can't seem to pass the HHVM check, it fails on ftell function saying tell is not supported, do you have any experience maybe with this and a way to overcome it?

2017-03-19 08:29 UTC, splitbrain commented
It's weird. From what I can see hhvm should support ftell. It might be that travis is running a rather outdated release. However I was thinking about the approach to rewrite the header size when a file size change was detected.

All we know is that the file changed between when we started reading it and when we finished. We might have read garbage and just changing the header will not fix that. I think the cleaner approach would be to throw an exception and let the user handle it.

2017-03-19 09:00 UTC, splitbrain commented
Okay I figured out what's going on. You initially had problems with $this->fh not being a resource. This happens when a tbz is written (the file is openend with bzopen). There is no tell or seek support in bz streams which is what hhvm complains about.

I don't see a way to implement the feature as you imagined it with supporting bz2. The only way would be reading the whole file into memory and check it's length before writing it to the archive.

I'll add an exception.

2017-03-19 09:11 UTC, closed without merging